# Copyright (c) 2026 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

[workspace]
resolver = "2"
members = ["mup1", "coap", "yang", "rcc"]

[workspace.package]
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml_ng = "0.10"
ciborium = "0.2"
serialport = { version = "4", default-features = false }
ureq = "3"
flate2 = "1"
tar = "0.4"
clap = { version = "4", features = ["derive"] }
regex = "1"
