# Copyright (c) 2026 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

[workspace]
resolver = "2"
members = ["cbor", "mup1", "coap", "yang", "fercc"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yml = "0.0"
serialport = { version = "4", default-features = false }
flate2 = "1"
tar = "0.4"
clap = { version = "4", features = ["derive"] }
regex-lite = "0.1"
