# Copyright (c) 2026 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

[package]
name = "yang"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
cbor = { path = "../cbor" }
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
flate2.workspace = true
tar.workspace = true
regex.workspace = true
