# Copyright (c) 2026 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

[package]
name = "fercc"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "fercc"
path = "src/main.rs"

[dependencies]
cbor = { path = "../cbor" }
mup1 = { path = "../mup1" }
coap = { path = "../coap" }
yang = { path = "../yang" }
serde.workspace = true
serde_json.workspace = true
serde_yml.workspace = true
clap.workspace = true

[dev-dependencies]
flate2.workspace = true
tar.workspace = true
