# Copyright (c) 2026 Microchip Technology Inc. and its subsidiaries.
# SPDX-License-Identifier: MIT

[package]
name = "mup1cc"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "mup1cc"
path = "src/main.rs"

[dependencies]
mup1 = { path = "../mup1" }
coap = { path = "../coap" }
yang = { path = "../yang" }
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
clap.workspace = true
ciborium.workspace = true
